// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://buvkkggimmpxgwquakuw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ1dmtrZ2dpbW1weGd3cXVha3V3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0MDU5MDAsImV4cCI6MjA3MTk4MTkwMH0.7HQuryJmqboHeVZ_fop0mrIS1UGBjkWHwIWefa5GSA8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});